a = input("birinci:")
b = input("ikinci:")
c = input("ucuncu:")
a= int(a)
b= int(b)
c= int(c)
print(("birinci sayısı {}'dir".format(a)),("ikinci sayısı {}'dir".format(b)),("ucuncu sayısı {}'dir".format(c)),sep="\n")
print("ucuncu çarpımı {} ".format(a*b*c))
print("{}x{}x{}={}".format(a,b,c,a*b*c))